name: Keep Render API Awake

on:
  schedule:
    - cron: '*/12 * * * *'  # Every 12 minutes
  workflow_dispatch:

jobs:
  ping-render-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check UTC Hour and Ping Render API
        run: |
          hour=$(date -u +"%H")
          if [ "$hour" -ge 0 ] && [ "$hour" -lt 1 ]; then
            echo "⏳ Skipping ping (00:00 - 01:00 UTC = 5:30 AM IST to 6:30 AM IST)"
            exit 0
          fi
          if [ "$hour" -ge 18 ] && [ "$hour" -lt 24 ]; then
            echo "⏳ Skipping ping (18:00 - 24:00 UTC = 11:30 PM IST to 5:30 AM IST)"
            exit 0
          fi

          # Otherwise, ping the Render API
          curl --silent --show-error --fail https://keepalive-backend.onrender.com/api/urls || echo "Ping failed"


# name: Keep Render API Awake

# on:
#   schedule:
#     - cron: '*/14 * * * *'  # Every 14 minutes
#   workflow_dispatch:

# jobs:
#   ping-render-api:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Curl ping to Render API
#         run: |
#           curl --silent --show-error --fail https://your-render-api-url.com/ping || echo "Ping failed"
