name: Keep Render API Awake
 
on:
  schedule:
    - cron: '*/12 * * * *'  # Every 12 minutes
  workflow_dispatch:

jobs:
  ping-render-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check UTC Hour and Ping Render API
        run: |
          hour=$(date -u +"%H")
          if [ "$hour" -lt 3 ] || [ "$hour" -ge 15 ]; then
            echo "⏳ Skipping ping (outside 3:00 - 14:59 UTC = 8:30 AM - 7:59 PM IST)"
            exit 0
          fi

          # Otherwise, ping the Render API
          curl --silent --show-error --fail https://keepalive-backend-imbv.onrender.com/api/urls || echo "Ping failed"

# name: Keep Render API Awake

# on:
#   schedule:
#     - cron: '*/14 * * * *'  # Every 14 minutes
#   workflow_dispatch:

# jobs:
#   ping-render-api:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Curl ping to Render API
#         run: |
#           curl --silent --show-error --fail https://your-render-api-url.com/ping || echo "Ping failed"
